apiVersion: v1
kind: Service
metadata:
  name: {APP_NAME}-service
spec:
  type: NodePort
  ports:
  - name: {APP_NAME}
    port: 8081
    nodePort: 31002
    targetPort: 8081
    protocol: TCP
  selector:
    app: {APP_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APP_NAME}-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {APP_NAME}
    spec:
      containers:
        - name: {APP_NAME}
          image: mzjvm:5000/{APP_NAME}:latest
          ports:
          - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {SPRING_PROFILE}