apiVersion: v1
kind: Service
metadata:
  name: mzjtestboot-service
spec:
  type: NodePort
  ports:
    - name: mzjtestboot
      port: 8280
      targetPort: 8280
      protocol: TCP
  selector:
    app: mzjtestboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mzjtestboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mzjtestboot
  template:
    metadata:
      labels:
        app: mzjtestboot
    spec:
      containers:
        - name: mzjtestboot
          image: mzjvm:5000/mzjtestboot:latest
          ports:
            - containerPort: 8280
          env:
            - name: SPRING_PROFILES_ACTIVE
              value:
